# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Snap Store

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Snap Store release channel'
        required: true
        default: 'latest/edge'
        type: choice
        options:
          - 'latest/edge'
          - 'latest/beta'
          - 'latest/candidate' 
          - 'latest/stable'

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v32.1.0

  release:
    name: Release snap
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_snap.yaml@v32.1.0
    with:
      channel: ${{ github.event.inputs.channel }}
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.SNAP_STORE_TOKEN }}
    permissions:
      contents: write  # Needed to create git tags